media:
  input: hugo/static/media
  output: /media

content:
  - name: general
    label: General
    type: file
    format: toml-frontmatter
    path: hugo/hugo.toml
    icon: file-cog
    fields:
      - name: title
        label: Title
        description: Website Title
        type: string
        required: true
      - name: legalLabel
        label: Title
        description: Link to the legal page
        type: string
        required: false
      - name: legalLink
        label: Title
        description: Label for the link to the legal page
        type: string
        required: false
      - name: developerLabel
        label: Title
        description: The name for the developers website
        type: string
        required: false
      - name: developerLink
        label: Title
        description: The link to the developers website
        type: string
        required: false

  - name: projects
    label: Projects
    type: file
    path: hugo/data/projects.yml
    icon: panels-top-left
    fields:
      - name: project
        label: Project
        type: object
        list: true
        fields:
        - name: title
          label: Title
          description: Project Name
          type: string
          required: true
        - name: logo
          label: Logo
          type: image
          required: true
          options:
            categories: [ image ]
        - name: backgroundImage
          label: Background Image
          type: image
          required: true
          options:
            categories: [ image ]
        - name: link
          label: Link
          type: string
          required: false